// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TNArchives_sos.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct TNSOS_SheetStylePropertyChangeSetArchive: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fill: TSDSOS_SpecFillArchive {
    get {_storage._fill ?? TSDSOS_SpecFillArchive()}
    set {_uniqueStorage()._fill = newValue}
  }
  /// Returns true if `fill` has been explicitly set.
  public var hasFill: Bool {_storage._fill != nil}
  /// Clears the value of `fill`. Subsequent reads from it will return its default value.
  public mutating func clearFill() {_uniqueStorage()._fill = nil}

  public var fillUndefined: Bool {
    get {_storage._fillUndefined ?? false}
    set {_uniqueStorage()._fillUndefined = newValue}
  }
  /// Returns true if `fillUndefined` has been explicitly set.
  public var hasFillUndefined: Bool {_storage._fillUndefined != nil}
  /// Clears the value of `fillUndefined`. Subsequent reads from it will return its default value.
  public mutating func clearFillUndefined() {_uniqueStorage()._fillUndefined = nil}

  public var tabFill: TSDSOS_SpecFillArchive {
    get {_storage._tabFill ?? TSDSOS_SpecFillArchive()}
    set {_uniqueStorage()._tabFill = newValue}
  }
  /// Returns true if `tabFill` has been explicitly set.
  public var hasTabFill: Bool {_storage._tabFill != nil}
  /// Clears the value of `tabFill`. Subsequent reads from it will return its default value.
  public mutating func clearTabFill() {_uniqueStorage()._tabFill = nil}

  public var tabFillUndefined: Bool {
    get {_storage._tabFillUndefined ?? false}
    set {_uniqueStorage()._tabFillUndefined = newValue}
  }
  /// Returns true if `tabFillUndefined` has been explicitly set.
  public var hasTabFillUndefined: Bool {_storage._tabFillUndefined != nil}
  /// Clears the value of `tabFillUndefined`. Subsequent reads from it will return its default value.
  public mutating func clearTabFillUndefined() {_uniqueStorage()._tabFillUndefined = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "TNSOS"

nonisolated extension TNSOS_SheetStylePropertyChangeSetArchive: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SheetStylePropertyChangeSetArchive"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fill\0\u{3}fill_undefined\0\u{3}tab_fill\0\u{3}tab_fill_undefined\0")

  fileprivate class _StorageClass {
    var _fill: TSDSOS_SpecFillArchive? = nil
    var _fillUndefined: Bool? = nil
    var _tabFill: TSDSOS_SpecFillArchive? = nil
    var _tabFillUndefined: Bool? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _fill = source._fill
      _fillUndefined = source._fillUndefined
      _tabFill = source._tabFill
      _tabFillUndefined = source._tabFillUndefined
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._fill, !v.isInitialized {return false}
      if let v = _storage._tabFill, !v.isInitialized {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._fill) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._fillUndefined) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._tabFill) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._tabFillUndefined) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._fill {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._fillUndefined {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._tabFill {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._tabFillUndefined {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: TNSOS_SheetStylePropertyChangeSetArchive, rhs: TNSOS_SheetStylePropertyChangeSetArchive) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._fill != rhs_storage._fill {return false}
        if _storage._fillUndefined != rhs_storage._fillUndefined {return false}
        if _storage._tabFill != rhs_storage._tabFill {return false}
        if _storage._tabFillUndefined != rhs_storage._tabFillUndefined {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
